### ISSUE TITLE
POS Spanish

### ISSUE THREAD

**Issue by galcivar** [nyxtom/salient#10]
Hi! Is there an example for https://github.com/nyxtom/salient#part-of-speech-tagging but in spanish?
Thanks

**Comment by nyxtom** [comment]
Hi there! Sorry for the late reply. The model for Spanish is in the bin directory as `es.hmm.json`. For the tree tagger you simply need to pass this model to the options.

```
var salient = require('salient');
var options = { model: "./path/to/bin/es.hmm.json" }
var hmmTagger = new salient.tagging.HmmTagger(options);
hmmTagger.tag([...]);
```
