### ISSUE TITLE
How can I use the spanish hmm?

### ISSUE THREAD

**Issue by edravis** [nyxtom/salient#3]
I don't get it. I though I have to initialize the hmm with `{ model: [pathToEShmm] }` but when I installed by `npm` I found that we don't have the `bin` folder.

So, I download the es.hmm.json file but it doesn't work at all.

Any idea?

**Comment by nyxtom** [comment]
I'm currently on leave but I will definitely look into this as soon as I can. I think I just need to rebuild the models or at least setup an easier method of producing them. In the mean time you can follow my hmm guide in the readme

**Comment by edravis** [comment]
Are you talking about this? [HMM_TRIGRAM.md](https://github.com/nyxtom/salient/blob/master/HMM_TRIGRAM.md)

If you're leaving does it means that Salient won't be supported anymore?

Thanks for reply and help ;)

**Comment by nyxtom** [comment]
I will be back from vacation in about 4 to 5 weeks. I should be able to handle it then.

**Comment by edravis** [comment]
Ooooh! I thought you were leaving for ever, nice so :P

**Comment by nyxtom** [comment]
Actually I just looked. The repo has a bin folder which contains the Spanish hmm model es.hmm.json this is the model you would use when creating the hmm tagger like so

```
var salient = require("salient")
var hmm = new salient.tagging.HmmTagger({ model: "./node_modules/salient/bin/es.hmm.json"})

hmm.Tag(....)
```

I also recommend using the Glossary part of the library. The options for that model can be done with

```
new salient.glossary.Glossary({lang: "es", model: "./node_modules/salient/bin/es.hmm.json"})
```

**Comment by nyxtom** [comment]
@edravis Does the above method work for you? Let me know if you need further help :)
