### ISSUE TITLE
npm install errors 

### ISSUE THREAD

**Issue by jamesbarros** [nyxtom/salient#4]
npm install salient fails. 
I'm on OSX 10.10.5
other npms install fine for me. 

output ends with: 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jbarros/Sites/emote/node_modules/salient/node_modules/iconv
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "salient"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@1.6.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbarros/Sites/emote/npm-debug.log

gist with full output and npm-install.log at 

https://gist.github.com/jamesbarros/001e28429563bc17931e

Please advise. Thank you.

**Comment by nyxtom** [comment]
I've run into this before, the best method is to blow away (delete) your ~/.node-gyp folder and try again.

**Comment by jamesbarros** [comment]
interesting. so I blew out ~/.node-gyp and retried, and get the same errors, but now from redis. 

npm ERR! hiredis@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbarros/Sites/emote/npm-debug.log



Am I going insane? 
Is there something stupid simple I should be doing that makes this work? 

Sorry for the newb questions. I'm still new to node.

**Comment by nyxtom** [comment]
Hmm, perhaps delete the node_modules directory as well? I would try npm install salient from a clean directory. I just updated the package as well.

**Comment by jamesbarros** [comment]
I'm really sorry, I don't know what broke, but I blew out my node-modules, re-installed, and everything is happy. THANK YOU :)

**Comment by nyxtom** [comment]
Awesome, no worries. Sorry about the mishaps :)
