### ISSUE TITLE
Glossary method doesn't work

### ISSUE THREAD

**Issue by soyjavi** [nyxtom/salient#5]
Hi :)

I'm taking a look of your project and I have a problem with method `glossary`. I'm using like your example and always returns `undefined`. 

```
import Salient from 'salient';
const glossary = new Salient.glossary.Glossary();
glossary.parse("This is going to be an awesome test");\
```

Any idea?

**Comment by nyxtom** [comment]
Sorry, I need to update my documentation on this, but parse actually doesn't return anything. It updates your `glossary` object in this case. You can use the results in different ways such as:

```
import Salient from 'salient';
const glossary = new Salient.glossary.Glossary();
glossary.parse("This is going to be an awesome test");
let result = glossary.toJSON();
let concepts = glossary.concepts();
```

That being said perhaps the API should be a bit simpler than that. Like parseConcepts() vs parse(). Nevertheless, it should still work :)

**Comment by nyxtom** [comment]
I have updated the README now, thanks! Let me know if you need any help :)

https://github.com/nyxtom/salient/commit/56e3e6cded9e5f97d9536aacdcaa588849e6a259

**Comment by soyjavi** [comment]
Thanks @nyxtom ... Kudos for you!!!
