### ISSUE TITLE
Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by dcsan** [nyxtom/salient#6]
I keep getting this on our production env despite trying node 5.9.1 and 6 
also `rm -rf node_modules` and reinstalling 

it works on local mac but not on production ubuntu 14

```
root/www/guessword/node_modules/salient/node_modules/node-expat/node_modules/bindings/bindings.js:83
guessword-1         throw e
guessword-1         ^
guessword-1 Error: Module version mismatch. Expected 47, got 46.
guessword-1     at Error (native)
guessword-1     at Object.Module._extensions..node (module.js:440:18)
guessword-1     at Module.load (module.js:357:32)
guessword-1     at Function.Module._load (module.js:314:12)
guessword-1     at Module.require (module.js:367:17)
guessword-1     at require (internal/module.js:16:19)
guessword-1     at bindings (/root/www/guessword/node_modules/salient/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
guessword-1     at Object.<anonymous> (/root/www/guessword/node_modules/salient/node_modules/node-expat/lib/node-expat.js:4:32)
guessword-1     at Module._compile (module.js:413:34)
guessword-1     at Object.Module._extensions..js (module.js:422:10)
```

**Comment by nyxtom** [comment]
I will be sure to take a look at this tomorrow morning. Thanks for the heads up

**Comment by nyxtom** [comment]
The best I could find on this issue seems to be related to the install setup:

http://stackoverflow.com/questions/15584529/module-version-mismatch-expected-11-got-1

**Comment by dcsan** [comment]
I'm using `n` to manage my node versions.
it apparently usually happens when you switch node versions - need to redo `npm install`
but that didn't work for me :(

**Comment by nyxtom** [comment]
I've had a few issues with `n` recently on some other projects. I've had to update my version of npm to resolve some of those issues. Right now I'm running:

```
nyxtom@higgs$ npm --version
3.10.10
~
nyxtom@higgs$ node --version
v7.3.0
```
