### ISSUE TITLE
unable to install through NPM

### ISSUE THREAD

**Issue by bansalvks** [nyxtom/salient#8]
C:\Users\vikas\Desktop\mydata\nlp project\salient>npm install --save salient
npm WARN package.json salient-app@1.0.0 No description
npm WARN package.json salient-app@1.0.0 No repository field.
npm WARN package.json salient-app@1.0.0 No README data
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git+https://github.com/nyxtom/redis-cluster.git resetting remote C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:829:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git+https://github.com/nyxtom/node-term-spinner.git resetting remote C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-node-term-spinner-git-41a3bbe8 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/nyxtom/redis-cluster.git C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874: Cloning into bare repository 'C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874'...
npm ERR! git clone --template=C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/nyxtom/redis-cluster.git C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874: fatal: unable to access 'https://github.com/nyxtom/redis-cluster.git/': Couldn't resolve host 'github.com'
npm ERR! git clone --template=C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/nyxtom/node-term-spinner.git C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-node-term-spinner-git-41a3bbe8: Cloning into bare repository 'C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-node-term-spinner-git-41a3bbe8'...
npm ERR! git clone --template=C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/nyxtom/node-term-spinner.git C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-node-term-spinner-git-41a3bbe8: fatal: unable to access 'https://github.com/nyxtom/node-term-spinner.git/': Couldn't resolve host 'github.com'
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "salient"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/nyxtom/redis-cluster.git C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874
npm ERR! Cloning into bare repository 'C:\Users\vikas\AppData\Roaming\npm-cache\_git-remotes\https-github-com-nyxtom-redis-cluster-git-abbaa874'...
npm ERR! fatal: unable to access 'https://github.com/nyxtom/redis-cluster.git/': Couldn't resolve host 'github.com'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vikas\Desktop\mydata\nlp project\salient\npm-debug.log

C:\Users\vikas\Desktop\mydata\nlp project\salient>

**Comment by nyxtom** [comment]
Interesting, the above errors seem to indicate that you are unable to access github itself and other repositories. Are you running into this with other npm installs?

**Comment by bansalvks** [comment]
Apologies!!

In my office do not why I am not able to install your repository through NPM. however, I am able to install other packages like express and others...

**Comment by nyxtom** [comment]
Odd!

```
nyxtom@higgs$ npm --version
3.10.10
```

```
nyxtom@higgs$ node --version
v7.3.0
```

```
nyxtom@higgs$ npm install --save salient

> iconv@2.2.1 install /Users/nyxtom/node_modules/iconv
> node-gyp rebuild

  CXX(target) Release/obj.target/iconv/src/binding.o
  CC(target) Release/obj.target/iconv/deps/libiconv/lib/iconv.o
  SOLINK_MODULE(target) Release/iconv.node

> node-expat@2.3.15 install /Users/nyxtom/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node

> hiredis@0.5.0 install /Users/nyxtom/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  LIBTOOL-STATIC Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/hiredis.node
npm WARN saveError ENOENT: no such file or directory, open '/Users/nyxtom/package.json'
/Users/nyxtom
└─┬ salient@0.2.1
  ├─┬ async@2.1.4
  │ └── lodash@4.17.4
  ├─┬ burst-trie@0.1.0
  │ └── underscore.string@2.2.1
  ├─┬ cli-color@1.1.0
  │ ├── ansi-regex@2.0.0
  │ ├── d@0.1.1
  │ ├─┬ es5-ext@0.10.12
  │ │ └── es6-symbol@3.1.0
  │ ├── es6-iterator@2.0.0
  │ ├─┬ memoizee@0.3.10
  │ │ ├─┬ es6-weak-map@0.1.4
  │ │ │ ├── es6-iterator@0.1.3
  │ │ │ └── es6-symbol@2.0.1
  │ │ ├── event-emitter@0.3.4
  │ │ ├── lru-queue@0.1.0
  │ │ └── next-tick@0.2.2
  │ └── timers-ext@0.1.0
  ├─┬ csv@1.1.0
  │ ├── csv-generate@1.0.0
  │ ├── csv-parse@1.1.8
  │ ├─┬ csv-stringify@1.0.4
  │ │ └── lodash.get@4.4.2
  │ └── stream-transform@0.1.1
  ├── he@0.5.0
  ├─┬ hiredis@0.5.0
  │ ├── bindings@1.2.1
  │ └── nan@2.5.0
  ├── iconv@2.2.1
  ├─┬ JSONStream@1.3.0
  │ ├── jsonparse@1.2.0
  │ └── through@2.3.8
  ├── minimist@1.2.0
  ├── node-expat@2.3.15
  ├─┬ node-redis-cluster@0.1.6  (git+https://github.com/nyxtom/redis-cluster.git#938bce5e4dcec84bb0d484535f4fbfc884d9e0b2)
  │ ├── async@0.2.10
  │ ├─┬ hashring@3.2.0
  │ │ ├── connection-parse@0.0.7
  │ │ └── simple-lru-cache@0.0.2
  │ └── redis@0.10.3
  ├─┬ plotter@0.4.3
  │ └── underscore@1.4.4
  ├── readline@0.0.3
  ├─┬ redis@2.6.3
  │ ├── double-ended-queue@2.1.0-0
  │ ├── redis-commands@1.3.0
  │ └── redis-parser@2.3.0
  ├─┬ redis-stream@0.1.0
  │ └─┬ event-stream@2.1.9
  │   ├── from@0.1.3
  │   ├─┬ optimist@0.2.8
  │   │ └── wordwrap@0.0.3
  │   └── through@0.0.4
  ├─┬ request@2.79.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.5.0
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.2
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├── has-ansi@2.0.0
  │ │ │ ├── strip-ansi@3.0.1
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@4.0.1
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.1
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.10.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.0
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.13
  │ │ └── mime-db@1.25.0
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.3.0
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.4.3
  │ └── uuid@3.0.1
  ├─┬ request-progress@3.0.0
  │ └── throttleit@1.0.0
  ├── robots@0.9.4
  ├── sylvester@0.0.21
  ├── term-spinner@1.0.0  (git+https://github.com/nyxtom/node-term-spinner.git#74b112debdca0eb98ed4e1c9248337e009a17bc1)
  ├── treetagger@0.1.1
  ├── twitter-text@1.6.1
  ├── underscore@1.5.2
  ├─┬ walk@2.2.1
  │ └─┬ forEachAsync@2.2.1
  │   └── sequence@2.2.1
  └─┬ xml-stream@0.4.5
    └─┬ readable-stream@1.1.14
      ├── core-util-is@1.0.2
      ├── inherits@2.0.3
      ├── isarray@0.0.1
      └── string_decoder@0.10.31

npm WARN enoent ENOENT: no such file or directory, open '/Users/nyxtom/package.json'
npm WARN nyxtom No description
npm WARN nyxtom No repository field.
npm WARN nyxtom No README data
npm WARN nyxtom No license field.
```

```
nyxtom@higgs$ node
> var salient = require('salient')
undefined
> salient.
salient.__defineGetter__      salient.__defineSetter__      salient.__lookupGetter__      salient.__lookupSetter__      salient.__proto__             salient.constructor
salient.hasOwnProperty        salient.isPrototypeOf         salient.propertyIsEnumerable  salient.toLocaleString        salient.toString              salient.valueOf

salient.classifiers           salient.corpus                salient.crawlers              salient.crossvalidation       salient.glossary              salient.graph
salient.language              salient.math                  salient.neuralnetworks        salient.normalizers           salient.regression            salient.sentiment
salient.tagging               salient.tokenizers            salient.wiktionary

> salient.
```

**Comment by nyxtom** [comment]
Let me know if you get it working or if you encounter something else :)
